name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only ai-carebot-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_USERNAME: ${{ secrets.SUPABASE_USERNAME }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          
